Elon Reeve Musk FRS (Pretória, 28 de junho de 1971) é um empreendedor,[3] empresário e filantropo sul-africano-canadense, naturalizado estadunidense. Ele é o fundador, diretor executivo e diretor técnico da SpaceX; CEO da Tesla, Inc.; vice-presidente da OpenAI, fundador e CEO da Neuralink; cofundador, presidente da SolarCity e proprietário do Twitter (X). Em 2023, ele era a pessoa mais rica do mundo, com um patrimônio líquido estimado em US$ 225 bilhões de dólares, de acordo com o Bloomberg Billionaires Index. Já a revista Forbes estimou sua fortuna em US$ 234 bilhões, principalmente de suas participações acionárias nas empresas Tesla e na SpaceX.[1][4]

Elon Musk nasceu em 28 de junho de 1971, em Pretória, Transvaal, África do Sul,[12] filho de Maye Musk (née Haldeman), modelo e nutricionista de Regina, Saskatchewan, Canadá, e Errol Musk, um engenheiro eletromecânico, piloto, marinheiro sul-africano, consultor e promotor imobiliário que já foi proprietário de metade de uma mina de esmeraldas na Zâmbia, perto do Lago Tanganica, o que ajudou a financiar o estilo de vida luxuoso de sua família adquirindo iates, férias em resorts de ski e computadores caros.[13][14][15]

Musk tem um irmão mais novo, Kimbal (nascido em 1972) e uma irmã mais nova, Tosca (1974).[16][17][18] Sua avó paterna era britânica e ele também possui ascendência holandesa.[19][20] Seu avô materno era estadunidense, de Minnesota.[21] Depois que seus pais se divorciaram em 1980, Musk viveu principalmente com seu pai nos subúrbios de Pretória,[19] mas que depois disse que "não foi uma boa ideia".[22] Depois de adulto, Musk cortou as relações com seu pai.[22] Também, ele tem uma meia-irmã.[23]

Durante a infância ele foi um ávido leitor.[24] Aos 10 anos, desenvolveu interesse em computação com o Commodore VIC-20.[25] Ele aprendeu de maneira autodidata programação de computadores aos 12 anos e vendeu o código de um jogo de vídeo baseado em BASIC que ele criou chamado Blastar para uma revista chamada PC and Office Technology por cerca de 500 dólares.[26][27] Uma versão web do jogo está disponível on-line.[26][28] Sua leitura da infância incluiu a Série da Fundação de Isaac Asimov, da qual ele tirou a lição de que "você deve tentar tomar o conjunto de ações que provavelmente prolongarão a civilização, minimizarão a probabilidade de uma idade das trevas e reduzirão o tamanho de uma era das trevas se houver uma."[22]

Musk sofreu severamente com bullying ao longo de sua infância,[22] e foi hospitalizado quando um grupo de meninos o jogou por um lance de escadas e depois o espancaram até perder a consciência.[24][29] Ele se mudou para o Canadá em junho de 1989, pouco antes do seu 18.º aniversário,[30] depois de obter a cidadania canadense através de sua mãe nascida no país.[31][32]
O foguete mais poderoso já desenvolvido na história está prestes a ser lançado pela primeira vez nesta segunda-feira (17/04).

O veículo, conhecido como Starship, foi construído pela companhia SpaceX, do empresário Elon Musk.

Ele tem quase 120 metros de altura e foi projetado para ter quase o dobro da propulsão de qualquer outro foguete já construído (veja detalhes abaixo).
Elon Musk tem vários filhos de relacionamentos anteriores e com sua atual parceira, a cantora Grimes. Musk tem cinco filhos com sua primeira esposa, Justine Musk, e um filho com sua segunda esposa, a atriz Talulah Riley. Com Grimes, Elon Musk tem um filho. Embora não haja muitas informações públicas sobre a dinâmica exata do relacionamento de Elon Musk com seus filhos, ele já mencionou em entrevistas e redes sociais que passa tempo com eles e que se preocupa com seu bem-estar. Além disso, Musk frequentemente compartilha fotos e histórias de suas interações com seus filhos em suas redes sociais, mostrando que ele valoriza seu papel como pai.


Elon Musk é pai de vários filhos de diferentes relacionamentos. Embora ele seja conhecido por ser bastante reservado sobre sua vida pessoal, ocasionalmente ele compartilha momentos com seus filhos nas redes sociais. Por exemplo, ele já postou fotos com seus filhos em eventos públicos ou ocasiões especiais. Musk também é conhecido por falar sobre a importância da família e da educação dos filhos em algumas entrevistas. No entanto, ele tenta manter a privacidade de sua família, evitando divulgar muitos detalhes sobre sua vida doméstica.








